In [27]:
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [28]:
# pull specific url for iowa wind farm data
url = "https://eersc.usgs.gov/api/uswtdb/v1/turbines?&t_state=eq.IA"

In [29]:
# ensure request goes through
print(requests.get(url))

<Response [200]>

In [30]:
# create response variable in json format
response = requests.get(url).json()

In [88]:
# print new dataframe for iowa wind farm data
iowa_df = pd.DataFrame(response)
iowa_df

,case_id,faa_ors,faa_asn,usgs_pr_id,t_state,t_county,t_fips,p_name,p_year,p_tnum,...,t_ttlh,t_conf_atr,t_conf_loc,t_img_date,t_img_srce,xlong,ylat,eia_id,retrofit,retrofit_year
0,3053390,19-028015,2015-WTE-6386-OE,NaN,IA,Boone County,19015,30 MW Iowa DG Portfolio,2017.0,10,...,150.0,3,3,6/1/2017,Digital Globe,-93.70042,41.97761,NaN,0,NaN
1,3049504,19-028019,2014-WTE-4171-OE,NaN,IA,Poweshiek County,19157,30 MW Iowa DG Portfolio,2017.0,10,...,150.0,3,3,1/28/2017,Digital Globe,-92.67209,41.74205,NaN,0,NaN
2,3063272,19-028134,2014-WTE-4084-OE,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,10,...,150.0,3,3,4/24/2017,Digital Globe,-93.43037,42.02823,NaN,0,NaN
3,3049502,19-027953,2014-WTE-4082-OE,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,10,...,150.0,3,3,5/13/2017,Digital Globe,-93.51808,42.01363,NaN,0,NaN
4,3063269,19-028130,2016-WTE-5934-OE,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,10,...,150.0,3,3,7/23/2017,Digital Globe,-93.63284,41.88248,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5946,3109434,None,2017-WTE-8857-OE,NaN,IA,Worth County,19195,unknown Worth County,2020.0,71,...,NaN,1,1,9/25/2020,Digital Globe,-93.11520,43.49437,NaN,0,NaN
5947,3106776,19-061455,2017-WTE-8898-OE,NaN,IA,Worth County,19195,unknown Worth County,2020.0,71,...,NaN,1,1,9/25/2020,Digital Globe,-93.03557,43.47940,NaN,0,NaN
5948,3110025,None,2017-WTE-8859-OE,NaN,IA,Worth County,19195,unknown Worth County,2020.0,71,...,NaN,1,1,9/25/2020,Digital Globe,-93.10191,43.49449,NaN,0,NaN
5949,3109301,None,2017-WTE-8888-OE,NaN,IA,Worth County,19195,unknown Worth County,2020.0,71,...,NaN,1,1,9/25/2020,Digital Globe,-93.11237,43.48038,NaN,0,NaN
5950,3109295,None,2017-WTE-8914-OE,NaN,IA,Worth County,19195,unknown Worth County,2020.0,71,...,NaN,1,1,9/25/2020,Digital Globe,-93.04032,43.46883,NaN,0,NaN

In [121]:
# drop all unnecessary columns
# iowa_df = iowa_df.drop(columns=['t_state','case_id','faa_ors','faa_asn','usgs_pr_id','t_fips','t_rsa','t_cap','t_ttlh','t_conf_atr', 't_conf_loc','t_img_date', 't_img_srce','eia_id', 'retrofit','retrofit_year'])

iowa_df = iowa_df[["t_county", "p_year", "p_cap", "p_name"]]
iowa_df

KeyError: "None of [Index(['t_county', 'p_year', 'p_cap', 'p_name'], dtype='object')] are in the [columns]"

In [90]:
# rename columns for cleaner look
iowa_df = iowa_df.rename(columns={'t_county':'County', 
                                  'p_year': 'Year', 
                                  'p_cap':'Cumulative Capacity of Wind Farm (in MW)',
                                  'p_name': "Wind Farm Name"
                                 })
iowa_df

,County,Year,Cumulative Capacity of Wind Farm (in MW),Wind Farm Name
0,Boone County,2017.0,30.0,30 MW Iowa DG Portfolio
1,Poweshiek County,2017.0,30.0,30 MW Iowa DG Portfolio
2,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
3,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
4,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
...,...,...,...,...
5946,Worth County,2020.0,NaN,unknown Worth County
5947,Worth County,2020.0,NaN,unknown Worth County
5948,Worth County,2020.0,NaN,unknown Worth County
5949,Worth County,2020.0,NaN,unknown Worth County
5950,Worth County,2020.0,NaN,unknown Worth County

In [91]:
# drop all years that have null values
iowa_df.dropna(subset=["Year"], inplace=True)
iowa_df

,County,Year,Cumulative Capacity of Wind Farm (in MW),Wind Farm Name
0,Boone County,2017.0,30.0,30 MW Iowa DG Portfolio
1,Poweshiek County,2017.0,30.0,30 MW Iowa DG Portfolio
2,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
3,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
4,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
...,...,...,...,...
5946,Worth County,2020.0,NaN,unknown Worth County
5947,Worth County,2020.0,NaN,unknown Worth County
5948,Worth County,2020.0,NaN,unknown Worth County
5949,Worth County,2020.0,NaN,unknown Worth County
5950,Worth County,2020.0,NaN,unknown Worth County

In [122]:
# drop all years that are older than 2000
current_ia_df = iowa_df[iowa_df["Year"] >= 2000].copy()
current_ia_df

,County,Year,Cumulative Capacity of Wind Farm (in MW),Wind Farm Name
0,Boone County,2017.0,30.0,30 MW Iowa DG Portfolio
1,Poweshiek County,2017.0,30.0,30 MW Iowa DG Portfolio
2,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
3,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
4,Story County,2017.0,30.0,30 MW Iowa DG Portfolio
...,...,...,...,...
5946,Worth County,2020.0,NaN,unknown Worth County
5947,Worth County,2020.0,NaN,unknown Worth County
5948,Worth County,2020.0,NaN,unknown Worth County
5949,Worth County,2020.0,NaN,unknown Worth County
5950,Worth County,2020.0,NaN,unknown Worth County

In [131]:
current_ia_df = current_ia_df.drop_duplicates(["Wind Farm Name"])

In [132]:
# current_ia_df.dropna(subset=["Cumulative Capacity of Wind Farm (in MW)"], inplace=True)
# current_ia_df

In [133]:
# showing all counties in iowa that have wind farms 
# current_ia_df["County"].value_counts()

In [134]:
# print clean iowa csv file for graphs and statistical analyses
#current_ia_df.to_csv("ia_clean.csv",
#                  encoding="utf-8", index=False, header=True)

In [135]:
# pull in population and unemployment csv file
csv_path = "../popn_and_unemployment.csv"
census_df = pd.read_csv(csv_path, encoding="utf-8")
census_df

,State,County,Year,Population,Unemployment Rate,2019 Median Income
0,OK,Oklahoma,2000,"3,454,365",3.0,NaN
1,OK,Adair County,2000,"21,031",2.6,NaN
2,OK,Alfalfa County,2000,"6,080",2.9,NaN
3,OK,Atoka County,2000,"13,820",3.6,NaN
4,OK,Beaver County,2000,"5,782",2.4,NaN
...,...,...,...,...,...,...
9355,IA,Winnebago County,2019,10354,5.7,59510.0
9356,IA,Winneshiek County,2019,19991,2.9,65482.0
9357,IA,Woodbury County,2019,103107,2.7,58419.0
9358,IA,Worth County,2019,7381,3.9,43142.0
9359,IA,Wright County,2019,12562,2.6,54251.0

In [136]:
census_df = census_df[["State", "County", "Year", "Population", "Unemployment Rate"]]
census_df

     State             County  Year Population  Unemployment Rate
0       OK           Oklahoma  2000  3,454,365                3.0
1       OK       Adair County  2000     21,031                2.6
2       OK     Alfalfa County  2000      6,080                2.9
3       OK       Atoka County  2000     13,820                3.6
4       OK      Beaver County  2000      5,782                2.4
...    ...                ...   ...        ...                ...
9355    IA   Winnebago County  2019      10354                5.7
9356    IA  Winneshiek County  2019      19991                2.9
9357    IA    Woodbury County  2019     103107                2.7
9358    IA       Worth County  2019       7381                3.9
9359    IA      Wright County  2019      12562                2.6

[9360 rows x 5 columns]

In [137]:
# filter out only iowa info
iowa_census = census_df[census_df["State"] == "IA"]
iowa_census

     State             County  Year Population  Unemployment Rate
78      IA       Adair County  2000      8,223                2.6
79      IA       Adams County  2000      4,476                2.8
80      IA   Allamakee County  2000     14,674                3.4
81      IA   Appanoose County  2000     13,696                4.3
82      IA     Audubon County  2000      6,804                2.9
...    ...                ...   ...        ...                ...
9355    IA   Winnebago County  2019      10354                5.7
9356    IA  Winneshiek County  2019      19991                2.9
9357    IA    Woodbury County  2019     103107                2.7
9358    IA       Worth County  2019       7381                3.9
9359    IA      Wright County  2019      12562                2.6

[1980 rows x 5 columns]

In [145]:
iowa_census.County.value_counts()

Cherokee County      20
Tama County          20
Van Buren County     20
Montgomery County    20
Wapello County       20
                     ..
Hamilton County      20
Delaware County      20
Howard County        20
Monona County        20
Lucas County         20
Name: County, Length: 99, dtype: int64

In [140]:
iowa_census.Year.nunique()

20

In [141]:
99 * 20

1980

In [143]:
current_ia_df.Year.nunique()

21

In [149]:
current_ia_df_grouped = current_ia_df.groupby(['County', 'Year']).sum()

current_ia_df_grouped = current_ia_df_grouped.reset_index()
current_ia_df_grouped

           County    Year  Cumulative Capacity of Wind Farm (in MW)
0    Adair County  2005.0                                      0.66
1    Adair County  2008.0                                    174.80
2    Adair County  2010.0                                      3.00
3    Adair County  2012.0                                    109.28
4    Adair County  2015.0                                      1.85
..            ...     ...                                       ...
112  Worth County  2001.0                                     80.10
113  Worth County  2008.0                                    109.70
114  Worth County  2009.0                                    160.00
115  Worth County  2011.0                                      3.20
116  Worth County  2021.0                                      0.00

[117 rows x 3 columns]

In [150]:
complete_iowa = pd.merge(current_ia_df_grouped, iowa_census, on=["County", "Year"], how="left")
complete_iowa

,County,Year,Cumulative Capacity of Wind Farm (in MW),State,Population,Unemployment Rate
0,Adair County,2005.0,0.66,IA,"7,932",4.0
1,Adair County,2008.0,174.80,IA,"7,747",4.1
2,Adair County,2010.0,3.00,IA,7682,5.5
3,Adair County,2012.0,109.28,IA,7468,4.4
4,Adair County,2015.0,1.85,IA,7145,3.2
...,...,...,...,...,...,...
112,Worth County,2001.0,80.10,IA,"7,797",5.1
113,Worth County,2008.0,109.70,IA,"7,632",6.7
114,Worth County,2009.0,160.00,IA,"7,610",10.1
115,Worth County,2011.0,3.20,IA,7561,11.5
116,Worth County,2021.0,0.00,NaN,NaN,NaN